[profile.default]
src = "src"                                               # Set the source directory.
test = "test"                                             # Set the test directory.
out = "out"                                               # Set the output directory for the artifacts.
libs = ["lib"]                                            # Configure an array of library directories.
cache = true                                              # Enable caching.
cache_path = "cache"                                      # Set the path to the cache.
force = false                                             # Do not ignore the cache.
solc_version = "0.8.33"                                   # Set the Solidity compiler version to ensure the same version is used across all chains.
evm_version = "paris"                                     # Set the EVM target version (prevent using the `PUSH0` and newer opcodes).
optimizer = true                                          # Enable the Solidity compiler optimiser.
optimizer_runs = 10_000_000                               # Configure the number of optimiser runs.
via_ir = true                                             # Compiles through the Yul intermediate representation ensuring fallback does not have freemem setup
bytecode_hash = "none"                                    # Remove the metadata hash from the bytecode to ensure reproducible builds when comments change.
cbor_metadata = false                                     # Disable the CBOR metadata (bytecode_hash, compiler version, etc.) suffix.
verbosity = 3                                             # Set the verbosity level for the tests - log by default.
fs_permissions = [{ access = "read", path = "./" }]       # Configure read-only access to the project root.
fuzz = { runs = 1024 }                                    # Configure the number of fuzz runs for the tests.
invariant = { runs = 256, depth = 15 }                    # Configure the number of runs and calls (executed in one run) for each invariant test group.

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "preserve"
hex_underscore = "preserve"
override_spacing = true
wrap_comments = true
ignore = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
